# golangci-lint configuration
# See https://golangci-lint.run/usage/configuration/

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - gosec
    - gocritic
    - bodyclose
    - durationcheck
    - errorlint
    - goconst
    - gocyclo
    - revive
    - unconvert
    - unparam

run:
  timeout: 5m
  tests: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
